using UglyToad.PdfPig;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using Microsoft.AspNetCore.Http;
using System.Text;
using AIResumeAnalyzer.MVC.Models;

namespace AIResumeAnalyzer.MVC.Services
{
    public class PdfService
    {
        public async Task<string> ExtractTextFromPdfAsync(IFormFile file)
        {
            if (file == null || file.Length == 0) return string.Empty;

            using var memoryStream = new MemoryStream();
            await file.CopyToAsync(memoryStream);
            memoryStream.Position = 0;

            var result = new StringBuilder();
            using (var document = UglyToad.PdfPig.PdfDocument.Open(memoryStream))
            {
                foreach (var page in document.GetPages())
                {
                    result.Append(page.Text);
                }
            }

            return result.ToString();
        }

        public string GenerateQuestionsPdf(string detectedRole, List<string> questions)
        {
            var directory = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "pdfs");
            if (!Directory.Exists(directory)) Directory.CreateDirectory(directory);

            var fileName = $"InterviewQuestions_{Guid.NewGuid()}.pdf";
            var path = Path.Combine(directory, fileName);

            using var writer = new PdfWriter(path);
            using var pdf = new iText.Kernel.Pdf.PdfDocument(writer);
            using var document = new Document(pdf);

            document.Add(new Paragraph($"Interview Questions: {detectedRole}")
                .SetTextAlignment(TextAlignment.CENTER)
                .SetFontSize(20));

            document.Add(new Paragraph("\n"));

            foreach (var q in questions)
            {
                document.Add(new Paragraph($"{q}").SetFontSize(12));
                document.Add(new Paragraph("\n"));
            }

            return $"/pdfs/{fileName}";
        }

        public string GenerateAnalysisPdf(Resume resume)
        {
            var directory = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "pdfs");
            if (!Directory.Exists(directory)) Directory.CreateDirectory(directory);

            var fileName = $"AnalysisReport_{Guid.NewGuid()}.pdf";
            var path = Path.Combine(directory, fileName);

            using var writer = new PdfWriter(path);
            using var pdf = new iText.Kernel.Pdf.PdfDocument(writer);
            using var document = new Document(pdf);

            // Header
            document.Add(new Paragraph("ORBIT AI: Resume Gap Analysis")
                .SetTextAlignment(TextAlignment.CENTER)
                .SetFontSize(22));

            document.Add(new Paragraph($"Candidate: {resume.OriginalFileName} | Date: {resume.UploadedAt:MMM dd, yyyy}")
                .SetTextAlignment(TextAlignment.CENTER)
                .SetFontSize(10));

            document.Add(new Paragraph("\n"));

            // Summary Table
            document.Add(new Paragraph("1. Executive Summary").SetFontSize(16));
            document.Add(new Paragraph($"Detected Role: {resume.DetectedRole}").SetFontSize(12));
            document.Add(new Paragraph($"ATS Compatibility Score: {resume.AtsScore}/100").SetFontSize(12));
            document.Add(new Paragraph($"Job Description Match: {resume.SkillMatchPercentage}%").SetFontSize(12));

            document.Add(new Paragraph("\n"));

            // Missing Skills
            document.Add(new Paragraph("2. Critical Missing Keywords").SetFontSize(16));
            if (resume.MissingSkills.Any())
            {
                var list = new iText.Layout.Element.List().SetListSymbol("\u2022");
                foreach (var skill in resume.MissingSkills)
                {
                    list.Add(new ListItem(skill));
                }
                document.Add(list);
            }
            else
            {
                document.Add(new Paragraph("No major skill gaps detected. Great job!"));
            }

            document.Add(new Paragraph("\n"));

            // Suggestions
            document.Add(new Paragraph("3. Orbit AI Recommendations").SetFontSize(16));
            if (resume.Suggestions.Any())
            {
                var list = new iText.Layout.Element.List().SetListSymbol("\u2022");
                foreach (var suggestion in resume.Suggestions)
                {
                    list.Add(new ListItem(suggestion));
                }
                document.Add(list);
            }
            else
            {
                document.Add(new Paragraph("No specific recommendations at this time."));
            }

            document.Add(new Paragraph("\n\n"));
            document.Add(new Paragraph("This report was automatically generated by Orbit AI.")
                .SetTextAlignment(TextAlignment.CENTER)
                .SetFontSize(9));

            return $"/pdfs/{fileName}";
        }
    }
}
